#each route discribed how an incoming url will be prossed by platfporm.sh

"http://{{default}}/":
    type: upstream
    upstream: "ll_project:http"

"https://www.{default}/":
    type: redirect
    to: "https://{default}/"
  

#each server listed with be deployed in its own container as part of your 
# patform.sh project.

db:
    type: postgresql:14
    disk: 1024
